### PR TITLE
use canned recipe, add .gitignore

### PR DESCRIPTION
**Pull request by livibetter**
Previously, only the last `cc` would have `-std=c11`. In my environment, the following error occurs:

```
error: 'for' loop initial declarations are only allowed in C99 mode
```

`-Wsign-compare` is turned on via `-Wextra`.

### CODE REVIEW

**Comment by zacariaz** [comment]
Ok, have spend the last half hour looking into makefiles, and I must admit I have really gotten that far. I've never really used them before, so there you go. I sure I'll get the hang of it all in good time, but as for your commit, it doesn't seem to make any sense, or work for that matter. As I said, I'll look into it.

I don't know what to make of the error you mention. Can I perhaps get some more information, like which files or files are involved and the position mentioned in said files?

**Comment by livibetter** [comment]
In my environment, `cc -c -o c2048.o c2048.c` got that error with GCC 4.8.4.

**Comment by livibetter** [comment]
@zacariaz You are using GCC 5, right? It has switched to `-std=gnu11`, that's why you didn't get the error. The real issue is you used `-std=c11`, but they,`c2048.c` and `main.c`, all compiled with `gnu11`

```
cc -c -o c2048.o c2048.c
cc -c -o main.o main.c
cc -o c2048 main.o c2048.o -l ncurses -std=c11 -Wall -pedantic -Wsign-compare
```

And `-Wall` and the rest is never going to be effective for compilation, since they are only used for the linking, that's the last `cc` line.

This is why I used canned recipe, it's simpler and cleaner, and less misunderstanding.

**Comment by zacariaz** [comment]
I've updated the makefile. Hopefully it's better, though I will of course continue to look into it.
And yes, it would appear that I'm using gcc 5.1.

What do you mean by 'canned recipe'. Is it a github or makefile thing? I'm sorta new to both.

**Comment by livibetter** [comment]
I misused the term, what I meant was the [Built-In Rules](https://www.gnu.org/software/make/manual/html_node/Catalogue-of-Rules.html#Catalogue-of-Rules) for C.

**Pull request closed without merging**
